'use strict';

var TRANSLATIONS = {
  en: {
    appTitle: 'Milk Price Calculator',
    subtitle: 'Daily tracking & billing',
    startDate: 'Start Date',
    endDate: 'End Date',
    pricePerLitre: 'Price per Litre (₹)',
    defaultMilk: 'Milk per Day (litres)',
    buyerName: 'Buyer Name',
    buyerNamePlaceholder: 'Optional',
    generate: 'Generate Bill',
    date: 'Date',
    day: 'Day',
    milk: 'Milk (L)',
    remark: 'Remark',
    totalMilk: 'Total Milk',
    totalAmount: 'Total Amount',
    print: 'Print / Save PDF',
    days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    rangeError: 'Date range cannot exceed 31 days.',
    endBeforeStart: 'End date must be after start date.',
    reset: '← New Bill',
    langToggle: 'हिंदी',
    litres: 'L',
    errorRequired: 'This field is required.',
    errorPositive: 'Must be greater than 0.',
    legendExtra: 'Extra milk',
    legendLess: 'Less milk',
    editHint: 'Tap any milk value to edit',
    slNo: '#',
    defaultLabel: 'default',
    printTitle: 'Milk Bill',
    priceLabel: 'Rate',
    perLitre: '/litre',
    // Banner
    bannerBadge: '🥛 Instant Milk Bill Generator',
    bannerHeadline1: 'From Milk to Bill,',
    bannerHeadlineAccent: 'Calculate',
    bannerHeadline2: 'in Seconds.',
    bannerSubtitle: 'Stop doing math on paper. Enter dates, set your rate — get a ready-to-share bill in seconds.',
    chip31days: '📅 Monthly billing',
    chipEdit: '✏️ Edit any day',
    chipPrint: '🖨 Share / Print PDF',
    chipLang: '🇮🇳 Hindi · English',
    bannerCta: 'Generate My Bill →',
    floatFresh: '🐄 Daily delivery tracked!',
    floatNoSurprise: '₹ Crystal clear bill 💯',
    saveImage: 'Save Image',
    receiptPreview: 'Receipt Preview',
    downloadImage: 'Download Bill',
    shareImage: 'Share Bill',
  },
  hi: {
    appTitle: 'दूध हिसाब कैलकुलेटर',
    subtitle: 'दैनिक ट्रैकिंग और बिलिंग',
    startDate: 'शुरू की तारीख',
    endDate: 'अंतिम तारीख',
    pricePerLitre: 'प्रति लीटर कीमत (₹)',
    defaultMilk: 'प्रतिदिन दूध (लीटर)',
    buyerName: 'खरीदार का नाम',
    buyerNamePlaceholder: 'वैकल्पिक',
    generate: 'बिल बनाएं',
    date: 'तारीख',
    day: 'दिन',
    milk: 'दूध (ली.)',
    remark: 'टिप्पणी',
    totalMilk: 'कुल दूध',
    totalAmount: 'कुल राशि',
    print: 'प्रिंट / PDF सहेजें',
    days: ['रवि', 'सोम', 'मंगल', 'बुध', 'गुरु', 'शुक्र', 'शनि'],
    months: ['जन', 'फ़र', 'मार्च', 'अप्रैल', 'मई', 'जून', 'जुलाई', 'अग', 'सित', 'अक्ट', 'नव', 'दिस'],
    rangeError: 'तारीख की सीमा 31 दिनों से अधिक नहीं हो सकती।',
    endBeforeStart: 'अंतिम तारीख शुरू की तारीख के बाद होनी चाहिए।',
    reset: '← नया बिल',
    langToggle: 'English',
    litres: 'ली.',
    errorRequired: 'यह फ़ील्ड आवश्यक है।',
    errorPositive: '0 से अधिक होना चाहिए।',
    legendExtra: 'अधिक दूध',
    legendLess: 'कम दूध',
    editHint: 'संपादित करने के लिए मूल्य पर टैप करें',
    slNo: '#',
    defaultLabel: 'डिफ़ॉल्ट',
    printTitle: 'दूध बिल',
    priceLabel: 'दर',
    perLitre: '/लीटर',
    // Banner
    bannerBadge: '🥛 झटपट दूध बिल बनाएं',
    bannerHeadline1: 'दूध का पूरा हिसाब,',
    bannerHeadlineAccent: 'एक क्लिक',
    bannerHeadline2: 'में बिल तैयार',
    bannerSubtitle: 'कागज़ पर हिसाब लगाना बंद करें। तारीख और दाम डालें — पल भर में बिल तैयार, शेयर करने को।',
    chip31days: '📅 मासिक बिलिंग',
    chipEdit: '✏️ कोई भी दिन बदलें',
    chipPrint: '🖨 शेयर / PDF प्रिंट करें',
    chipLang: '🇮🇳 हिंदी · अंग्रेज़ी',
    bannerCta: 'मेरा बिल बनाएं →',
    floatFresh: '🐄 रोज़ की डिलीवरी ट्रैक!',
    floatNoSurprise: '₹ साफ़ और पक्का बिल 💯',
    saveImage: 'इमेज सहेजें',
    receiptPreview: 'रसीद पूर्वावलोकन',
    downloadImage: 'बिल डाउनलोड करें',
    shareImage: 'बिल शेयर करें',
  }
};
