'use strict';

var TRANSLATIONS = {
  en: {
    appTitle: 'Milk Price Calculator',
    subtitle: 'Daily tracking & billing',
    startDate: 'Start Date',
    endDate: 'End Date',
    pricePerLitre: 'Price per Litre (₹)',
    defaultMilk: 'Milk per Day (litres)',
    buyerName: 'Buyer Name',
    buyerNamePlaceholder: 'Optional',
    generate: 'Generate Bill',
    date: 'Date',
    day: 'Day',
    milk: 'Milk (L)',
    remark: 'Remark here..',
    totalMilk: 'Total Milk',
    totalAmount: 'Total Amount',
    print: 'Print / Save PDF',
    days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    rangeError: 'Date range cannot exceed 31 days.',
    endBeforeStart: 'End date must be after start date.',
    reset: '← New Bill',
    langToggle: 'हिंदी',
    litres: 'L',
    errorRequired: 'This field is required.',
    errorPositive: 'Must be greater than 0.',
    legendExtra: 'Extra milk',
    legendLess: 'Less milk',
    editHint: 'Tap any milk value to edit',
    slNo: '#',
    defaultLabel: 'default',
    printTitle: 'Milk Bill',
    priceLabel: 'Rate',
    perLitre: '/litre',
    // Banner
    bannerBadge: '🥛 Instant Milk Bill Generator',
    bannerHeadline1: 'From Milk to Bill,',
    bannerHeadlineAccent: 'Calculate',
    bannerHeadline2: 'in Seconds.',
    bannerSubtitle: 'Stop doing math on paper. Enter dates, set your rate — get a ready-to-share bill in seconds.',
    chip31days: '📅 Monthly billing',
    chipEdit: '✏️ Edit any day',
    chipPrint: '🖨 Share / Print PDF',
    chipLang: '🇮🇳 Hindi · English',
    bannerCta: 'Generate My Bill →',
    floatFresh: '🐄 Daily delivery tracked!',
    floatNoSurprise: '₹ Crystal clear bill 💯',
    saveImage: 'Share Bill',
    receiptPreview: 'Receipt Preview',
    downloadImage: 'Download Bill',
    shareImage: 'Share Bill',
    addToHome: 'Add to Home Screen',
  },
  hi: {
    appTitle: 'दूध हिसाब कैलकुलेटर',
    subtitle: 'दैनिक ट्रैकिंग और बिलिंग',
    startDate: 'शुरू की तारीख',
    endDate: 'अंतिम तारीख',
    pricePerLitre: 'प्रति लीटर कीमत (₹)',
    defaultMilk: 'प्रतिदिन दूध (लीटर)',
    buyerName: 'खरीदार का नाम',
    buyerNamePlaceholder: 'वैकल्पिक',
    generate: 'बिल बनाएं',
    date: 'तारीख',
    day: 'दिन',
    milk: 'दूध (ली.)',
    remark: 'टिप्पणी लिखें',
    totalMilk: 'कुल दूध',
    totalAmount: 'कुल राशि',
    print: 'प्रिंट / PDF सहेजें',
    days: ['रवि', 'सोम', 'मंगल', 'बुध', 'गुरु', 'शुक्र', 'शनि'],
    months: ['जनवरी', 'फरवरी', 'मार्च', 'अप्रैल', 'मई', 'जून', 'जुलाई', 'अगस्त', 'सितम्बर', 'अक्टूबर', 'नवम्बर', 'दिसम्बर'],
    rangeError: 'तारीख की सीमा 31 दिनों से अधिक नहीं हो सकती।',
    endBeforeStart: 'अंतिम तारीख शुरू की तारीख के बाद होनी चाहिए।',
    reset: '← नया बिल',
    langToggle: 'English',
    litres: 'ली.',
    errorRequired: 'यह फ़ील्ड आवश्यक है।',
    errorPositive: '0 से अधिक होना चाहिए।',
    legendExtra: 'अधिक दूध',
    legendLess: 'कम दूध',
    editHint: 'संपादित करने के लिए मूल्य पर टैप करें',
    slNo: '#',
    defaultLabel: 'डिफ़ॉल्ट',
    printTitle: 'दूध बिल',
    priceLabel: 'दर',
    perLitre: '/लीटर',
    // Banner
    bannerBadge: '🥛 झटपट दूध बिल बनाएं',
    bannerHeadline1: 'दूध का पूरा हिसाब,',
    bannerHeadlineAccent: 'एक क्लिक',
    bannerHeadline2: 'में बिल तैयार',
    bannerSubtitle: 'कागज़ पर हिसाब लगाना बंद करें। तारीख और दाम डालें — पल भर में बिल तैयार, शेयर करने को।',
    chip31days: '📅 मासिक बिलिंग',
    chipEdit: '✏️ कोई भी दिन बदलें',
    chipPrint: '🖨 शेयर / PDF प्रिंट करें',
    chipLang: '🇮🇳 हिंदी · अंग्रेज़ी',
    bannerCta: 'मेरा बिल बनाएं →',
    floatFresh: '🐄 रोज़ की डिलीवरी ट्रैक!',
    floatNoSurprise: '₹ साफ़ और पक्का बिल 💯',
    saveImage: 'बिल शेयर करें',
    receiptPreview: 'रसीद पूर्वावलोकन',
    downloadImage: 'बिल डाउनलोड करें',
    shareImage: 'बिल शेयर करें',
    addToHome: 'होम स्क्रीन पर जोड़ें',
  },
  hr: {
    appTitle: 'दूध का हिसाब-किताब',
    subtitle: 'रोज़ का लेखा-जोखा, सही-सही',
    startDate: 'कद तै शुरू करां?',
    endDate: 'कद तक चाहिए?',
    pricePerLitre: 'लीटर का भाव (₹)',
    defaultMilk: 'रोज़ कितना दूध (लीटर)',
    buyerName: 'किसके नाम पे बिल बणावा?',
    buyerNamePlaceholder: 'छोड़ दे, चालेगा',
    generate: 'बिल काढ़ दे भाई',
    date: 'तारीख',
    day: 'दिन',
    milk: 'दूध (ली.)',
    remark: 'कोई खास बात ?',
    totalMilk: 'पूरा दूध',
    totalAmount: 'टोटल पैसे',
    print: 'छाप दे / PDF बना दे',
    days: ['इतवार', 'सोमवार', 'मंगलवार', 'बुधवार', 'बीरवार', 'शुक्रवार', 'शनिवार'],
    months: ['जनवरी', 'फरवरी', 'मार्च', 'अप्रैल', 'मई', 'जून', 'जुलाई', 'अगस्त', 'सितम्बर', 'अक्टूबर', 'नवम्बर', 'दिसम्बर'],
    rangeError: 'भाई, 31 दिन तै ज्यादा मत माँग!',
    endBeforeStart: 'रे भाई/बहन तारीख तो ठीक ते भर ल। आखिरी तारीख पहली तारीख से पहल्या हो सके से, बता?',
    reset: '← नया बिल बणा ले',
    langToggle: 'English',
    litres: 'ली.',
    errorRequired: 'अरे भर दे यो खाना भी।',
    errorPositive: '0 तै ज़्यादा होणा चाहिए, भाई।',
    legendExtra: 'ज्यादा दूध आया',
    legendLess: 'कम दूध आया',
    editHint: 'दबा दे, बदल देगा',
    slNo: '#',
    defaultLabel: 'आम',
    printTitle: 'दूध का बिल',
    priceLabel: 'भाव',
    perLitre: '/लीटर',
    bannerBadge: '🥛 झटपट दूध का बिल बण्या',
    bannerHeadline1: 'दूध का पूरा हिसाब,',
    bannerHeadlineAccent: 'एक झटके में',
    bannerHeadline2: 'बिल तैयार।',
    bannerSubtitle: 'कागज़ पे हिसाब करणा छोड़ दे। तारीख अर भाव डाल — पल में बिल तैयार, भेज दे जिसनै चाहें।',
    chip31days: '📅 महीने का बिल',
    chipEdit: '✏️ कोई भी दिन बदल',
    chipPrint: '🖨 शेयर / PDF छाप',
    chipLang: '🇮🇳 हरियाणवी · हिंदी · English',
    bannerCta: 'मेरा बिल बणा दे →',
    floatFresh: '🐄 रोज़ की दूध ट्रैक होगी!',
    floatNoSurprise: '₹ साफ़-साफ़ बिल, कोई धोखा नहीं 💯',
    saveImage: 'बिल भेज दे',
    receiptPreview: 'रसीद देख ले',
    downloadImage: 'बिल उतार ले',
    shareImage: 'बिल भेज दे',
    addToHome: 'फ़ोन पे लगा दे',
  }
};
